modLoader="javafml"
loaderVersion="[37,)"
license="Creative Commons Attribution-NonCommercial-NoDerivatives 4.0"

[[mods]]
modId="reworkedmetals"
version="2.0.1"
displayName="Reworked Metals"
displayURL="\n    https://www.curseforge.com/minecraft/mc-mods/reworked-metals\n"
logoFile="ReworkedMetals.png"
credits="\n    Author: HexagonNico \n    Russian translation: Remivy12345\n"
description='''
A rework of Minecraft's metalworking system
'''

[[dependencies.reworkedmetals]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.reworkedmetals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="AFTER"
    side="BOTH"
