modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"

[[mods]]
modId="reworkedmetals"
version="0.1"
displayName="Reworked Metals"
logoFile="logo.png"
authors="HexagonNico"
description='''
A rework of Minecraft's metalworking system.
'''

[[dependencies.reworkedmetals]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.reworkedmetals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="AFTER"
    side="BOTH"
