modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons Attribution-NonCommercial-NoDerivatives 4.0"
issueTrackerURL="https://github.com/HexagonNico/ReworkedMetals/issues"

[[mods]]
modId="reworkedmetals"
version="2.0.1"
displayName="Reworked Metals"
displayURL="https://www.curseforge.com/minecraft/mc-mods/reworked-metals"
logoFile="ReworkedMetals.png"
#credits=""
authors="HexagonNico"
description='''
A rework of Minecraft's metalworking system
'''

[[dependencies.reworkedmetals]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.reworkedmetals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="AFTER"
    side="BOTH"
