modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="reworkedmetals"
version="1.0"
displayName="Reworked Metals"
logoFile="logo.png"
authors="HexagonNico"
description='''
A rework of Minecraft's metalworking system.
'''

[[dependencies.reworkedmetals]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.reworkedmetals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="AFTER"
    side="BOTH"
